name: Check

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install tox poetry

      - name: Show versions
        run: |
          uname -a
          python3 --version
          echo "tox: $(tox --version)"
          poetry --version

      - run: tox -e lint

  tests:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.10"]
        # include:
        #   - os: macos-12
        #     python-version: "3.11"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install tox poetry

      - name: Show versions
        run: |
          uname -a
          python3 --version
          echo "tox: $(tox --version)"
          poetry --version

      - run: tox -e tests
        # Run tox using py: The current Python version tox is using

  build:
    needs: tests
    name: Build distribution packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install poetry

      - name: Show versions
        run: |
          uname -a
          python3 --version
          poetry --version

      - run: poetry build
