name: Check

on: [push]

# Read-only on contents; 
# it should break if there is need to upgrade requirements lockfiles
permissions:
  contents: read

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Get pip cache dir
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        # no hardcode os-specific path
        id: pip-cache-dir
      - name: Cache ${{ steps.pip-cache-dir.outputs.dir }}
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: pip-${{ github.job }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: pip-${{ github.job }}

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Show versions
        run: |
          uname -a
          python3 --version
          hatch --version

      - name: Run static analysis
        run: hatch fmt --check

      - name: Run types check
        run: hatch run types:check

  tests:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}

    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        # no hardcode os-specific path
        id: pip-cache-dir
      - name: Cache ${{ steps.pip-cache-dir.outputs.dir }}
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: pip-${{ github.job }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: pip-${{ github.job }}-${{ matrix.os }}-${{ matrix.python-version }}-

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Show versions
        run: |
          uname -a
          python3 --version
          hatch --version

      - name: Run tests
        run: hatch test --cover

  build:
    needs: tests
    name: Build distribution packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Get pip cache dir
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        # no hardcode os-specific path
        id: pip-cache-dir
      - name: Cache ${{ steps.pip-cache-dir.outputs.dir }}
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: pip-${{ github.job }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: pip-${{ github.job }}-

      - name: Install build
        run: pip install --upgrade build

      - name: Show versions
        run: |
          uname -a
          python3 --version
          python3 -m build --version

      - name: Build distributions
        run: python3 -m build
