name: Release

on:
  release:
    types: [published]

jobs:

  publish:
    name: Build and publish Python distribution to PYPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install supporting packages
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install poetry

      - name: Show versions
        run: |
          uname -a
          python3 --version
          poetry --version

      - name: Build wheel and source tarball
        run: |
          poetry build

      - name: Publish distribution to PIPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
